### ISSUE TITLE
Breaking changes MapLibre GL JS v5

### ISSUE THREAD

**Issue by sbachinin** [maplibre/maplibre-gl-js#3834]
This issue is to track breaking changes for MapLibre GL JS v5:

- [x]  queryTerrainElevation should return meters above sea level. (Currently it returns a special offset used for positioning of custom 3d objects). - #3854
- [x] getElevationOffset method should be added. It should return the offset that is currently retrieved from queryTerrainElevation - there is elevation definition now as part of the spec.
- [x] https://github.com/maplibre/maplibre-style-spec/pull/519
- [x] #3898
- [x] https://github.com/maplibre/maplibre-gl-js/pull/3136#issuecomment-2101231496
- [x] Fix sky for globe - #4853
- [x] Fix performance issues for globe related to `projectAndGetPerspectiveRatio` - #4778
- [x] Add projection outside the style for initialization much like zoom/breaking etc. - #4909
- [x] Add more parameters to custom layer to better support globe
- [x] ~Geojson close to the poles with globe - https://github.com/maplibre/maplibre-gl-js/discussions/1598#discussioncomment-10538001, https://github.com/maplibre/maplibre-gl-js/pull/3963#issuecomment-2344778823~ - this is a limitation of mercator coordinates system.
- [x] Return value for `on` method to allow unsubsribing - #5080
- [x] Change how bearing and roll UX on desktop when dragging - https://github.com/maplibre/maplibre-gl-js/pull/4780#discussion_r1803869111, #5074
- [x] Globe showstpeer issues (terrain + globe is not a showstopper as one can disable terrain for lower zoom levels when globe is on): https://github.com/maplibre/maplibre-gl-js/labels/showstopper
- [x] Incorporate globe, vertical-perspective and expression for projection - #5139, #5114 , #5056
- [x] Move webgl initialization configuration into an object to future proof it - #5135, #5198

**Comment by sbachinin** [comment]
This is likely to produce breaking changes: https://github.com/maplibre/maplibre-gl-js/issues/3736:
- `queryTerrainElevation` should return meters above sea level. (Currently it returns a special offset used for positioning of custom 3d objects).
- `getElevationOffset` method should be added. It should return the offset that is currently retrieved from queryTerrainElevation

**Comment by HarelM** [comment]
The following issue will also create breaking change to the output of `geometry-type`:
- https://github.com/maplibre/maplibre-gl-js/issues/3516

This issue has a part in the style-spec repo as well.
- https://github.com/maplibre/maplibre-style-spec/pull/519

**Comment by wipfli** [comment]
I am happy with breaking changes in the API of MapLibre GL JS, but we should not do breaking changes in the style spec, see https://github.com/maplibre/maplibre-style-spec/pull/519#issuecomment-2017725720. In my opinion, `geometry-type` should keep the same behavior as it did so far.

**Comment by HarelM** [comment]
I respect your opinion but I don't agree in this specific case, see my comment in the link you sent. TL;DR: more in the area of bug fix and not a style spec change.

**Comment by birkskyum** [comment]
Depending on when this release is to come out ( looking at our majors, it's statistically likely to be +6 months from now ), it might be relevant to discuss a WebGL1 sunset again. We had some push back in the v3 release May 2023, but there are some indicators that it might be problematic going forward. We're already now increasingly alone in keeping WebGL1 at the cost of locking the renderer to a legacy graphics pipeline. MapLibre Native sunset OpenGL2 (~webgl1) in favor of OpenGL3+ (webgl2) to do the Modularization refactor, and it would be necessary to do something similar here as well.

**Comment by HarelM** [comment]
Is there a way you can think of to allow moving the webgl1 code into a plugin somehow leaving the main version using only webgl2 but allowing this plugin to try and "help" in case someone needs webgl1?

**Comment by HarelM** [comment]
Another candidate for v5 breaking changes:
- #3898

**Comment by wipfli** [comment]
Let's discuss phasing out webgl1 in a separate thread here: #3947

**Comment by HarelM** [comment]
As part of this issue: 
- #3878

I found out that freeze elevation is not the default when doing easeTo when terrain is on.

I think it should be, so that it is consistent with pan movement. 
This is a breaking change, so I'm writing it here.

**Comment by birkskyum** [comment]
v5 Breaking change:
- CustomRenderMethod should take an options object https://github.com/maplibre/maplibre-gl-js/pull/3136#issuecomment-2101231496

**Comment by birkskyum** [comment]
The arial font - I'd love to see it gone from the default, because it's always a problem to source it. 
- https://github.com/maplibre/maplibre-style-spec/pull/436

**Comment by wipfli** [comment]
I think we should have a discussion in the next monthly meeting how we want to handle breaking style changes. API changes are something different.

**Comment by birkskyum** [comment]
> Is there a way you can think of to allow moving the webgl1 code into a plugin somehow leaving the main version using only webgl2 but allowing this plugin to try and "help" in case someone needs webgl1?

The only way I see that we can realistically keep webgl1 support is by abstraction:
- #4511 

A key difference is how uniforms are made:

|        | individual uniforms | uniform buffer objects (UBOs) |
|--------|--------------------|-----------------------------|
| webgl1 | x                  |                             |
| webgl2 | x                  | x                           |
| webgpu |                    | x                           |


So we'll be going through a transition like [this](https://github.com/visgl/deck.gl/issues/8997), where webgl2 can be leveraged as a transition technology towards webgpu. In MapLibre Native, the opengl2(webgl1) was sunset to allow for this incremental migration, but it seems here that we'll need to keep webgl1 around. @zhangyiatmicrosoft do you have any idea where the usage numbers are for webgl1 now, compared to the numbers you presented a year ago [here](https://github.com/maplibre/maplibre-gl-js/issues/2653)?

**Comment by HarelM** [comment]
It would also be interesting to see if we can both abstract and allow webgl1 to be moved outside the code base, allowing the code to be fully webgl2 or even abstract enough to require another package defining the GL itself - i.e. abstract and also separate to core, webgl1, webgl2, webgpu so that developer can choose which to support/include.
